apiVersion: 1

datasources:
  - name: InfluxDB-UniFi
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: home
      defaultBucket: unifi
    secureJsonData:
      token: ${INFLUXDB_TOKEN}
    isDefault: true
    editable: true
